otris/ews-cpp

CMakeLists.txt
include/ews/rapidxml/rapidxml.hpp

Added -Wpedantic and some more warning flags to GCC's command line

GCC: more pedantic warning level

---

CMakeLists.txt
include/ews/ews.hpp
include/ews/rapidxml/rapidxml.hpp
tests/fixtures.hpp
tests/gtest-wrapper.hpp
tests/main.cpp
tests/test_internals.cpp

This PR increases Clang's warning-level significantly.
We already have GCC with pedantic in master. Merging this branch makes clang++ more nitpicking, too.
Changes:
- switch warning level from -Wall to -Weverything and turn off unneeded or unwanted warnings explicitly
- turn on color in diagnostics explicitly as terminal detection does not always seem to work
- wrap <gtest/gtest.h> in new header file, switch off some noisy warnings from Google Test framework
- and last but not least, fix some harmless warnings in rapidxml.hpp and ews.hpp

Increase clang warning level

---

include/ews/ews.hpp
include/ews/ews_fwd.hpp
tests/test_service.cpp

Introduce `ews::update` class. `update` class renders a single
<SetItemField>, <AppendToItemField>, or <DeleteItemField> operation. The
constructor of update is a converting c'tor which renders a
<SetItemField> of a given property by default.
Introduce an update_item overload set:
- item_id update_item(item_id, update, ...) and
- item_id update_item(item_id const std::vector<update>&, ...)
Fixes issue #16

Make update_item support set, append, and delete

---

include/ews/ews.hpp
tests/fixtures.hpp
tests/test_attachments.cpp
tests/test_items.cpp
tests/test_service.cpp

This commit implements the class extended_property which holds the class extended_field_uri as member containing the following attributes:
- distinguished_property_set_id
- property_set_id
- property_tag
- property_id
- property_type
There are five constructors for all valid combinations of the attributes and a getter/setter for each.
Two static members converts the attributes to_ and from_xml.
see [MSDN: ExtendedProperty](https://msdn.microsoft.com/en-us/library/office/aa566405(v=exchg.150).aspx)
see [MSDN: ExtendedFieldURI] (https://msdn.microsoft.com/en-us/library/office/aa564843(v=exchg.150).aspx)
This commit will fix issue #7

Implement extended_properties

---

.appveyor.yml
.travis.yml
README.md

Add  continuous integration with [AppVeyour](https://ci.appveyor.com) on Windows and [Travis](https://travis-ci.org) on Linux/OSX.
The files .appveyor.yml and .travis.yml are new and README.md is showing status badges of that builds. 
Everything works fine except of all tests and compiling with clang-3.5 on Travis.
This will fix issue "Add public CI" #25.

Add Travis & AppVeyor build support and badges

---

.appveyor.yml
.travis.yml
README.md

Fix for Travis & AppVeyor build support and badges
The README.md shows Travis' g++ build as failed, because the whole set, g++ & clang, fails. 
I changed this behaviour to represent the real state of every single build. I marked missing builds with a comment: "* = CI will be implemented soon"
This change will last until clang, Visual Studio 2012 and/or Linux 32bit builds will be implemented.

Fix for Travis & AppVeyor build support and badges

---

CMakeLists.txt

Pass -pg option to g++ to generate additional profile infos for tools such as [gprof](https://sourceware.org/binutils/docs/gprof/) and [uftrace ](https://github.com/namhyung/uftrace) when needed.

Add option to generate profile info on gcc

---

examples/autodiscover.cpp
include/ews/ews.hpp
include/ews/ews_fwd.hpp
tests/fixtures.hpp
tests/test_autodiscover.cpp

This pr removes the unneeded autodiscover_protocol type and implements autodiscover_result and autodiscover_hints, which are now both implemented in the get_exchange_web_services_url functions.
The function now has an overload, so the autodiscover_hints parameter is optional.
The tests and the autodiscover.cpp example have also been adjusted.

Make autodiscover great again -- The second coming

---

include/ews/ews.hpp
tests/test_items.cpp

To use the create_item functions with multiple of items I added the following things:
- create_item overloads for all items, including calendar items
and message items 
- add documentation
- add tests for creating items with vector

Extend create_item overload set to handle multiple items

---

include/ews/ews.hpp
tests/test_items.cpp

The send_item functions can now be used with `std::vector<item_id>` which is needed for sending multiple messages at once.

Add send_item bulk operation overloads

---

.travis.yml

The docs are now automatically created and pushed to gh-pages, the only step still needed for this repository is creating said branch:
https://gist.github.com/vidavidorra/548ffbcdae99d752da02#create-a-clean-gh-pages-branch
In total:
- The .travis.yml has been cleaned up
- The .travis.yml has been adjusted to autodeploy
The output of said deployment can be seen [here](https://github.com/m-Schlitzer/ews-cpp/tree/gh-pages). This pull request closes #67 .

Autodeploy Doxygen docs to GH pages

---

include/ews/ews.hpp

Add the `const` modifier to allow using these functions, so we can work on a `const contact` object, such as in ews-ja-api.

Add const modifier to get_file_as, get_file_as_mapping

---

tests/fixtures.hpp
tests/test_attachments.cpp

This commit adds a `\0` to the vector returned from the read_file overload, and removes the unnecessary push_backs in the attachment_tests.

Add null terminator to read_file func

---

CMakeLists.txt
examples/resolve_names.cpp
include/ews/ews.hpp
include/ews/ews_fwd.hpp
tests/assets/resolve_names_error.xml
tests/assets/resolve_names_response.xml
tests/fixtures.hpp
tests/test_resolve_names.cpp

This pull request closes #73 . 
The contact part of the resolution only contains the DirectoryId, because the returned response from the exchange server doesn't include an ItemId, which is needed for creation of a contact.
Also, because of this fact, the function now only needs the name to look for, the ParentFolderIds and the searchscope.

Add <ResolveNames> operation and example

---

include/ews/ews.hpp

My first time contributing a project on GitHub or using git, so bear with me.
Exchange is limiting the search results to 1000 due to the EWS throttling (https://msdn.microsoft.com/en-us/library/office/jj945066(v=exchg.150).aspx) defined in the EWSFindCountLimit value.
Using the paging search as specified here: https://msdn.microsoft.com/en-us/library/office/dn592093(v=exchg.150).aspx
I added an overload to the find_item(...) message of base_service. It gets a const ref to an object of the new class paging_view (based on the calendar_view class). This object defines the number of item IDs to return, the offset and the base point (which is basically the direction). Using the advance() public member function, the offset can be advanced between the subsequent calls of find_item(...).
The base …

Paged search

---

examples/create_folder.cpp
examples/delete_folder.cpp
examples/find_folder.cpp
examples/get_folder.cpp
include/ews/ews.hpp
include/ews/ews_fwd.hpp

I implemented the create_folder, delete_folder, find_folder and get_folder operations. It should have the same convention as the item operations.
There are still some operations missing, like CreateManagedFolder, CopyFolder, MoveFolder, EmptyFolder, UpdateFolder.

Add folder operations

---

.gitmodules

These commit change the gtest submodule to my fork, where I removed the -Werror flag causing some of our builds to fail.

Remove gtest submodule -Werror

---

include/ews/ews.hpp

The overload of get_folder_impl without the additional_properties
parameter was checking said parameter.

Remove invalid EWS_ASSERT in get_folder_impl

---

CMakeLists.txt
examples/subscribe.cpp
include/ews/ews.hpp
include/ews/ews_fwd.hpp
tests/assets/subscribe_response.xml
tests/fixtures.hpp
tests/test_subscribe.cpp

This pull request implements the [Notification operations](https://msdn.microsoft.com/en-us/library/office/bb409286(v=exchg.150).aspx#Anchor_9)  as wanted in #80 . 
Done:
- [\<Subscribe\> operation](https://msdn.microsoft.com/en-us/library/office/aa566188(v=exchg.150).aspx)
- The `event_type` enum class has been added to correctly use all available `event_types`. At least one of these are mandatory per request according to EWS. 
- The `subscription_information` struct contains the `subscription_id` and `watermark` which are needed for furhter use. This object is returned by the `subscribe` function.
- Tests have been added as well to check the validity of the parsed information and the send request.
- [\<Unsubscribe\> operation](https://msdn.microsoft.com/en-us/library/office/aa564263(v=ex …

WIP: Implement notification operations

---

include/ews/ews.hpp

Removes the warning produced by probably uninitialized unread_count_ member.

Correctly initialize modified_event

---

.travis.yml

The local_dir option was wrong, after the newest travis update it seems. https://github.com/travis-ci/travis-ci/issues/9047

Fix travis ci gh-pages deployment

---

include/ews/ews.hpp

I was working on an implementation  for recurring items.
I added the new class occurrence_item_id which is basically an regular item_id with an integer specifying the occurrence id of a recurring item.
New overloads of get_calendar_item take the occurrence_item_id instead of a regular item_id and return the particular occurrence of the recurring calendar item.
I didn't add any tests or examples and to be honest, I won't have the time to do that any time soon. Because it turns out that we won't support recurring calendar items in our system for now.
I hope you can merge it anyways. Would be a shame if it goes to waste.

OccurrenceItemId

---

.appveyor.yml
CMakeLists.txt
Jenkinsfile
README.md
include/ews/ews.hpp
tests/fixtures.hpp
tests/test_attachments.cpp
tests/test_autodiscover.cpp
tests/test_items.cpp
tests/test_resolve_names.cpp
tests/test_service.cpp
tests/test_subscribe.cpp

Remove Boost.Filesystem dependency
Use std::filesystem instead. Since most compilers and development environments already support C++17 std::filesystem it doesn't make sense to require an extra-heavy dependency like Boost anymore for running some additional tests.

Remove boost

---

CMakeLists.txt
Jenkinsfile
include/ews/ews.hpp
include/ews/ews_fwd.hpp
tests/assets/bogus_server.py
tests/test_timeout.cpp

Address issue #111 by always enabling run-time checks.
Overview of the changes in this PR:
- EWS_ASSERT is now a normal function (`ews::check`) that throws an exception instead of triggering a SIGABRT via assert(3)
- every run-time check that was EWS_ASSERT before is now always enabled, this of course includes release builds
- there is now a little Python HTTP server that returns a fake response
If we want to guard against more bogus responses or even against malicious servers we need to do more testing, though. (Maybe fuzzing could help here?)

More careful response parsing

---

include/ews/ews.hpp

The ItemShape note was missing the BaseShape note. Instead it
had the actual id_only shape as the value of ItemShape.
I guess it only worked because the Exchange server ignored
the value and defaulted to id_only.
It was
`<ItemShape>
Default
</ItemShape>`
instead of
`<ItemShape>
<t:BaseShape>Default</t:BaseShape>
</ItemShape>`

Fix SyncFolderItems requested shape

---

examples/sync_folder_hierarchy.cpp
include/ews/ews.hpp

Regarding #123
All seems pretty straight forward.
It works just like SyncFolderItems.
Call the sync function without the sync state to start the initial synchronization. 
From this point on, just reuse the previously received sync state.
The only thing worth mentioning is the deleted_folder_ids of the return value.
Contrary to the sync_folder_items_result, the sync_folder_hierarchy has containers
with the 'whole' folders (ID, display name, child folder count, total item count,
unread item count) for created and updated folders. But for deleted folders it has
a container with folder IDs.

Sync folder hierarchy

---

include/ews/ews.hpp

Some fixes regarding folders and their respective functions.
Most important is a fix on get_folder_impl which caused an compilation error when used.
I still don't understand why it did compile in the first place.

Folder fixes

---

include/ews/ews.hpp

Regarding Issue #131 
The response contains information of items whose read flag changed.
Including a bool with true for read and false for unread. This hasn't
been parsed correctly and always returned false for each element.

Fix parsing of SyncFolderItems response

---

include/ews/ews.hpp

Regarding issue #138 get_room_lists from outlook.com
When the response of GetRoomLists has the ResponseClass Error, we
immediately throw an exchange_error. Instead of expecting the
RoomLists element to be there and throwing an assertion_error. The
Exchange server behind outlook.com (formerly hotmail.com) doesn't
allow access to room management.

Fix parsing of GetRoomLists response on error

---

include/ews/ews.hpp

Regarding #134 
The ews docu doesn't specify any element of mailbox as mandetory. And
evidently mailboxes without address nor ID do exist.

Remove check for address in mailbox

---

include/ews/ews.hpp

In regards to #144 
I added functions to return if the attachment is inlined
in an item and the Content-ID of that attachment.

Add content_id and is_inline to ews::attachment

---

examples/update_contact.cpp
include/ews/ews.hpp
tests/test_contacts.cpp

Add and fix some of the contact property paths to allow
updating the various phone numbers and physical address entries.
Though it has to be mentioned, updating the physical address is a
little tedious. Each item of a physical address requires it's own update
item. So, when creating a physical_address item for an update, only
one of the address items has to be set. The others have be left empty.
I added examples to the update_contact.cpp example which shows
how the city and the street is updated.
Regarding issue #141

Contact property paths

---

CMakeLists.txt
examples/update_extended_property.cpp
include/ews/ews.hpp

Reworked and expanded extended_property with to_xml and from_xml_element.
The first one is relevant for the ability to update extended_properties, because I changed update to store a property as a string instead of a property. This way we can support extended_property easily.
Should close #142 .

Support updating extended properties

---

include/ews/ews.hpp

When parsing SyncFolderHierarchy response the child element had to be
"Folder". Which is not the case for non mail folders like calendar
folders or contact folders. Now it accepts any kind of child element,
expecting it to have a folder_id inside.
One of our customers had a calendar folder in his inbox. Not sure how.
Neither Outlook nor OWA allows the creation of a non-mail folder in
inbox.
Though I did manage to reproduce it using Microsofts EwsEditor.

Fix folder type restriction

---

include/ews/ews.hpp

The element `<DirectoryId/>` is optional
Closes #151

Fix ResolveNames operation parsing error

---

include/ews/ews.hpp
tests/assets/resolve_names_response.xml
tests/test_resolve_names.cpp

First implementation for providing the Contact information in a Resolve Names resolution. The shared_ptr is used for the time being, but its use revised late.

Add support of Contact information in Resolve Names resolutions

---

include/ews/ews.hpp

The conversion functions for event_type were missing the
event_type::moved_event case.
I was looking into Pull-Subscriptions when I noticed that those
functions seemed a bit off. I hope this event wasn't missing
intentionally. But I couldn't imagine a reason why it would.

Fix event_type to and from string

---

include/ews/ews.hpp

The Attendee element was missing potential ProposedStart and
ProposedEnd child elements. Those were missing from Microsoft
documentation. They are used when an attendee proposes a different
date and time for the meeting.
I already created a pull request for Microsofts docs. But the types
schema shows that ProposedStart and ProposedEnd are possible
child elements.
BTW: The Mailbox child element is now mandatory. I'm pretty sure
this is correct. But the type schema doesn't sepecify this element with
'required'.

Fix Attendee element

---

include/ews/ews.hpp

It's now possible to request the mime content when retrieving an item
attachment. The attachment class has a function to extract the mime
content of the attached item.
I needed to get the item attachments as a file.
To do so, I added the option to request the mime content when calling
get_attachment(...).
Apparently some xml tags in the GetAttachment operation had the
wrong namespace. (<m:IncludeMimeContent> instead of
<t:IncludeMimeContent>) Which wasn't that big of a problem, since
the tags were empty and supposed to define the default value.
But when I fixed the namespace, the exchange server complained about
the xml tags being invalid when they don't have a value.
As you can see in the get_attachment function, the
<t:IncludeMimeContent> tag works properly with either true or false
as …

Add mime content to item attachments

---

include/ews/ews.hpp

Makes handling of the constructor easier when not all features
are built-in into curl.
Relates to  #172

Set curl settings only when value diffrent than default value

---

include/ews/ews.hpp
tests/test_service.cpp

* Introduces a new enum `ssl_options' for SSL options supported by the underlying libcurl.
* Can be used to configuring the connection to the EWS service.
* Useful in the context of #172 where a man-in-the-middle proxies are used

Add SSL options for connecting to EWS service (#172)

---

include/ews/ews.hpp

Adding two methods:
* `set_server_uri()`: Sets the server URI of the service object
* `set_credentials()`: Sets the credentials of the service object

Method for setting server uri and credentials

---

include/ews/ews.hpp

Addition to #193, so that the Expect header is set empty automatically, if BASIC auth is used.

Set Expect header for BASIC auth (#193)

---

include/ews/ews.hpp

If OAuth2 is used, an connection is established immediately. Thus, in some cases a path the CA certificates is needed as well, if no default CA certificates are used.

Constructor with caPath arg

---

include/ews/ews.hpp

The CURL handle is copied for the OAuth login request. If the original handle was initialized with specific HTTPAUTH type, the request will not sent properly. This can result in a error message "AADSTS900144: The request body must contain the following parameter: 'grant_type'", as the body will not sent. Resetting the HTTPAUTH to the default value fixes this.
Also included, using CURL options for sending the bearer token.

Fixing OAUTH login request
